[pytest]
filterwarnings =
    # Convert all warnings to errors, except those we explicitly ignore.
    error
    ignore:The property ``qiskit.dagcircuit.dagcircuit.DAGCircuit.duration`` is deprecated as of qiskit 1.3.0*:DeprecationWarning
    ignore:The property ``qiskit.dagcircuit.dagcircuit.DAGCircuit.unit`` is deprecated as of qiskit 1.3.0*:DeprecationWarning
    ignore:The method ``qiskit.circuit.library.standard_gates.x.MCXGate.get_num_ancilla_qubits\(\)`` is pending deprecation as of qiskit 1.3*:PendingDeprecationWarning
